/*
        Home Work 5
        Done By : Abu Khan
        Date: October 2, 2014
 */

package bhc;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class BHCFrame extends javax.swing.JFrame {

    /**
     * Creates new form BHCFrame
     */
    public BHCFrame() {
        initComponents();
        //set current year, month, day as initial data
        Integer year =  2015;
        Integer month = 6;
        Integer day = 1;
        yearTextField.setText(year.toString());
        monthTextField.setText(month.toString());
        dayTextField.setText(day.toString());
        
        
        //set package tour list from homework 2
        packageComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gardiner Lake", "Hellroaring Plateau", "The Beaten Path" }));
        //set the number of days for the first tour as initial data
        numberofdaysComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"3", "5"}));
        // set rate for first tour
        basicRateLabel.setText("40");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalcostLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        monthTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        packageComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        numberofdaysComboBox = new javax.swing.JComboBox();
        calculateButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        basicRateLabel = new javax.swing.JLabel();
        totalcostResultLabel = new javax.swing.JLabel();

        totalcostLabel.setText("Total Cost:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beartooth Hiking Company(BHC)- Tour Cost Estimation Tool");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Tours are offered between June 1 to October 1 every year from 2014 to 2020");

        jLabel1.setText("Begin Date:");

        jLabel2.setText("Year(xxxx)");

        yearTextField.setText("xxxx");
        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Month");

        jLabel4.setText("Day:");

        jLabel5.setText("Tours:");

        packageComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        packageComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Number of Days:");

        numberofdaysComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        calculateButton.setText("Estimate Cost");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Basic rate/day: $");

        basicRateLabel.setText("jLabel9");

        totalcostResultLabel.setText("Total Cost:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalcostResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(packageComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(numberofdaysComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(basicRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(packageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(numberofdaysComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(basicRateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(totalcostResultLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void packageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedPackage = packageComboBox.getSelectedItem().toString();
        if (selectedPackage=="Hellroaring Plateau")
        {
            numberofdaysComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"2","3", "4"}));
            basicRateLabel.setText("35");
        }
        else if (selectedPackage=="Gardiner Lake")
        {
            numberofdaysComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"3", "5"}));
            basicRateLabel.setText("40");
        }
         else if (selectedPackage=="The Beaten Path")
         {
            numberofdaysComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"5", "7"})); 
            basicRateLabel.setText("45");
         }
         
    }//GEN-LAST:event_packageComboBoxActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // TODO add your handling code here:
        //check for valid start date
        try {
            if (yearTextField.getText().length()<4)
               JOptionPane.showMessageDialog(null,"Year needs to be of four(4) digits "  , "Error", JOptionPane.ERROR_MESSAGE); 
            else
            {
                    Integer year = Integer.parseInt(yearTextField.getText());
                    Integer month = Integer.parseInt(monthTextField.getText());
                    Integer day = Integer.parseInt(dayTextField.getText());
                    BookingDay startDate = new BookingDay(year,month,day );

                    if (startDate.isValidDate())
                    {
                        Rates rates = new Rates();
                        rates.setBaseRate(Integer.parseInt(basicRateLabel.getText()));
                        //set begin date
                        rates.setBeginDate(startDate);
                        Integer duration = Integer.parseInt(numberofdaysComboBox.getSelectedItem().toString());
                        Calendar gc =  new GregorianCalendar(year,month-1,day);
                        // System.out.println(gc.get(Calendar.DAY_OF_MONTH));
                        gc.add(Calendar.DATE,duration-1);
                        //System.out.println(gc.get(Calendar.DAY_OF_MONTH));
                        int endYear = gc.get(Calendar.YEAR);
                        int endMonth = gc.get(Calendar.MONTH);
                        int endDay = gc.get(Calendar.DAY_OF_MONTH);
                        BookingDay endDate = new BookingDay(endYear, endMonth+1, endDay);
                        System.out.println(endDate + "Start" + startDate);
                        if (endDate.isValidDate())
                        {
                             rates.setEndDate(endDate);
                              if (rates.isValidDates())
                              {
                                  totalcostResultLabel.setText("Total Cost: $"+ rates.getCost() + "   (Weekdays:"+ rates.getNormalDays() + "@ $" + rates.getBaseRate() + "  Weekends:" + rates.getPremiumDays()+"@ $" + rates.getPremiumRate()+")");

                              }
                              else
                              {
                                  totalcostResultLabel.setText("Total cost:");
                                  JOptionPane.showMessageDialog(null, " Sorry but " +rates.getDetails() , "Error", JOptionPane.ERROR_MESSAGE); 

                              }
                         }
                         else
                          {
                                 totalcostResultLabel.setText("Total cost:");
                                JOptionPane.showMessageDialog(null,"End Date, " + endDate.toString() + " is either out of calculation date limit or invalid date" , "Error", JOptionPane.ERROR_MESSAGE); 
                           }

                      }
                      else
                      {
                             totalcostResultLabel.setText("Total cost:");
                            JOptionPane.showMessageDialog(null,"Start Date, " + startDate.toString() + " is either out of calculation date limit or invalid date" , "Error", JOptionPane.ERROR_MESSAGE);

                      }
           
             }
        }
        catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, nfe.getLocalizedMessage() + " need integer value!"  , "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_calculateButtonActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BHCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BHCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BHCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BHCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BHCFrame().setVisible(true);
                 //basic rate
               // static int basicRate = 0;
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basicRateLabel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JComboBox numberofdaysComboBox;
    private javax.swing.JComboBox packageComboBox;
    private javax.swing.JLabel totalcostLabel;
    private javax.swing.JLabel totalcostResultLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
